language: scala
scala:
- 2.11.7
jdk:
- oraclejdk8
notifications:
  email: false
  slack:
    rooms:
      secure: bdhiqCalmH8H9So3iTYkQXsYtrNgWkzY6JZojZitPgpRw4QJRPleOIrp6he0i3f2fz6/cWpRbtGCFEEOxT36Knb7Ys2CGPglj0VnO1Q3Qr07W1j5CxWEfUwDo2bCz1F/OL42Sd7fQ+dGtb3sktV9xr5bqJNt/fDKbkWGGpBE4N+AT4aL6Ug712LX0G/IYkjYjqtmPilznN3zOI/3OWYOaS82gPREcX2vzrvMpFQmOY0vSYcZ0Ueu5nT+QcHc77qnSiWb/aI7bebaZnXJmfpwnDZkYm4xH0eINthh3ot5+FnD9d2CfWW2vmGSVQ8bnq/TP2Jw/eiikoy5UApHQO5SqNOXf/xG8TuoDoec+Oi6JrUJlC96LhawFQyQA3iGqmw75nmLfrs5epOFZOUTKR9NaXpNZTeSx/svqsusAF4SxLHfZHYJj8RfGVmRoyeiog0zyE40sbXj40g220+2ZiJ7MbZD3QgYK/rvecA3P0c5jGFhwtCH9hMyDRhEi+AEc1nIzNAyDZOoFBF9NJ5IRIEh6LgJbravfpb+7lRmr+z3gmVMCChrIkz0SEbelBvYFAX9PZOdsm0yuxRGXFLoTMECDtkJx9DVpaWzW0SYyprhAD69UTKp6fOrHj7Vd6ysREzHBRDO1LwPFWsP3/ueiz26shnJiehPIIacUo2fD+oGGK0=
    on_success: change
    on_failure: always
    on_start: never
    on_pull_requests: false
script:
- sbt clean coverage test
after_success:
- sbt coveralls
