language: scala

scala:
 - 2.11.7

jdk:
 - oraclejdk8

notifications:
  slack:
    secure: BtxKIxg6flG6E6g5mNBBBJGn/AgVCkLzsS/48nIzqcEfabZW1ThHXCalKKHwSmp34w+IpgzSTZ4b5nA2YqVCKjzv2EjR12Fqinv5tOoZqJUJ4f2DvMFnEjXYnVV7EStNF5zkpcKmMcbdgkY32IGsPQohpMLut4OUE03emceLy8m2pezdJKervXFR6x0FrpMbaFRrQ6gquF4klaI0r+QFgVavdmUhdbPJa0Yj7c0mhBz67V8+oU0glyEiQXkk+4dt4HmzK8J/JpC+dD69o5EiQxu1r0dFuE2nDeVe1AjTgh/AmTqOTSvj1mW7wPnSKyRqgMNLlsD9u/BAlMXOIvspj+osYFtk0bfyVAKmDAVVKy+tEMg7+A4B7Pw5Jhp3ixwIPF+rJoW1tYW59qF4tPUau0ESmnP7G3K+obynLZWIwGfrRvML6MPYG2X8lhAMmwH30IJcPG06mEfpF9VYsj1Zmr6+lYGw2s7gY9jG9r0uJQD3QP10cVSl4E43mPPM2eWJzrQ9LbkqIDjghM6J4NfjGolzZ1nkOM+zTqhPQ09ZF205hDrkJ20/G1OocZaln7AgLet++onB3Fw7yTMfsKnV2iRvh2zO/gKZ6UHr/Yg1y1zB5j322M66KjKOM3akvad93VGZtwQwEbqbhieRyDKV9WEf0zMGFZpefFd8H1iBngE=
    on_success: change
    on_failure: always
    on_start: never

env:
  global:
    secure: RULmUvid7xU/YDyYYkUSk0CbXEG/EpfxMfxJ5qMwCQYZbg5BklIhnrEpVwq9Ylfg7i51h+qjdKYwlwxAAyBiMn1VSxNM5OIyzEkC2sr86FcgbnSaTWx1os7MzN4DgnKozpdcL/uMoekbWuXu4GzgUxKlttEZXh+7+aaWHqqnTdspXjnR9OA1P4rwcK9k4CUCJTWjoP5tDRmwtYCb46aZ1pePTtmtpMSow3xSx0Vu5LgQvQJhkpMMFl5pyPh2KKqUN52Cb7xKluN5fCJZjDQDiPVJ5RCSJgTRcLr8sjQS7UJ08pctU6BoIpPNiguFpQACxnhhzEClhUlzJxa3jSSG8lWk5wYOP5z891mpjrAkoalJQknvFE4u+SVnt4bmwTQr+oUn1+KCA0ba0ckaTjX49Te+fSuBbno4p65xeG7+a/Tmix4Qe/Q2cYPyzuGLixIoaZWPmouK/VLXrc4bpWgevzyX2nE0yMDS+TvkXh4plJ7xUb1lDF26okC9Is2XyKi6tHM/JJemy3Nq6svNPOioo0bLgPAKp+Cemz+/KzbMm4NMSw+bI7wj/2xZN1OjhS6U/TZoVW60rmzfJGc1olM9rNpHjMux92OmNUz6o2AqLg70o/7KySX1T72SOldcILcUfC90kzBi+ayFx4KTipIfkDdUACBgEYRp/cE+tLraKjs=

script:
 - sbt clean coverage test

after_success:
 - sbt coveralls
