language: scala
scala:
- 2.11.7
jdk:
- oraclejdk8
notifications:
  email: false
  slack:
    rooms:
      secure: Xb/nHT4WlznAdTXc/NbZ4a2xSjuwz//ecTZAS9ze2l5Cvrd6QVV3ff/+M4QNmodMZOBZ0BEEpIdBuPy6N8v+cfFF/SyJQzPKLU6JtC3pVTFVdqgAgtjM9Osy+1/1QrbZb54wkZnsFq059eGM7lqilDnxVhUz0gPZOhT9nGk/DMiiLbWwZdfes/MBfZCuTOuqG4S/NJsv7nxdmjPM9D+oFbvPIQesLLDqO+3azW8QpikAPoK7P88wE5Tp3IAeLEFtcqqMfDOwvNS6U8VCtjH2/3vCj5PNNlnxuESpzDjJRdBM1BurRszZ7VSbvha7yObnXKTbwAf6LJNIDHhCEnLpadNVsEmSxy6Fdl9TKYZ3RMIJ/v2fU4vfwW4i3S+M+B62YEJRA0XGuRd+dxhf2gmc0dDk6uC2VPKyddb1CWRrHMtRo4GgWTnlVllifrKWDJAS2ymEhcwkcXa3Y0x64WuaYwUEzQi2LHT4Qc9DJNLJphd3C7CSBMlmwGpQnqeWr5NH8Rfgp/ogRDbUNdUp+bONUf7Q+q4Q8pHnsKOgA8xflBoPh4mQSh9Xc0gtaMT8OECR0h2331s5KXTSOmKNisuahRdHR37RFj2E009GWzc4fqOE00IHUd9PgpDW41zv+4mAv/ZywL/A8kaNtz2LJ2OJG/6ryj3/9WoolNRMLhP2az4=
    on_success: always
    on_failure: always
    on_start: never
    on_pull_requests: false
script:
- sbt clean coverage test
after_success:
- sbt coveralls
