DROP TABLE chat_offers;
DROP TABLE msg_ack;
DROP TABLE msg_history;
DROP TABLE refresh_tokens;
DROP TABLE authorization_codes;
DROP TABLE third_party_accounts;
DROP TABLE google_accounts;
DROP TABLE passwords;
DROP TABLE accounts;
